logger:
  level: ${LOGGER_LEVEL:-info}

server:
  use_reflection: ${SERVER_USE_REFLECTION:-true}
  port_grpc: ${SERVER_PORT_GRPC:-50051}
  port_http: ${SERVER_PORT_HTTP:-8080}
  http_read_timeout: ${SERVER_HTTP_READ_TIMEOUT:-30}
  http_write_timeout: ${SERVER_HTTP_WRITE_TIMEOUT:-30}
  http_idle_timeout: ${SERVER_HTTP_IDLE_TIMEOUT:-120}
  http_read_header_timeout: ${SERVER_HTTP_READ_HEADER_TIMEOUT:-10}
  graceful_shutdown_timeout: ${SERVER_GRACEFUL_SHUTDOWN_TIMEOUT:-5}

gateway:
  cors_allowed_origins: ${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://localhost:5173,http://localhost:8080,http://localhost:8082}
  cors_max_age: ${CORS_MAX_AGE:-86400}
  rate_limit_rps: ${RATE_LIMIT_RPS:-100}
  rate_limit_burst: ${RATE_LIMIT_BURST:-10}

swagger:
  port: ${SWAGGER_PORT:-8082}

